import type { RunReport } from '../schemas/run-report.js';
import type { TestPlan } from '../schemas/test-plan.js';

/**
 * The pull-request title and body.
 *
 * Pure — takes plans and a run report, returns markdown. A reviewer opening
 * this PR has one question: **should I trust these tests?** So the body leads
 * with what actually ran, not with what was generated. A wall of "12 tests
 * added" that turns out to be 9 skips is how a generated PR gets rubber-stamped
 * once and distrusted forever.
 *
 * Everything that did not pass is named, with its reason. That includes the
 * ones Flint could not fix: a `fixme` in the diff with no explanation in the
 * body is a reviewer's problem, and it should have been ours.
 */

export interface PrContentOptions {
  plans: TestPlan[];
  /** Absent when `--no-verify` was used — the body says so rather than implying green. */
  report?: RunReport;
  baseUrl: string;
  /** Feature ids this PR covers, for the title. */
  featureIds: string[];
}

export interface PrContent {
  title: string;
  body: string;
}

export function buildPrContent(options: PrContentOptions): PrContent {
  return { title: buildTitle(options), body: buildBody(options) };
}

function buildTitle(options: PrContentOptions): string {
  const ids = [...options.featureIds].sort();
  if (ids.length === 0) return 'test: update the generated Playwright suite';
  if (ids.length === 1) return `test: generated Playwright coverage for ${ids[0]}`;
  if (ids.length <= 3) return `test: generated Playwright coverage for ${ids.join(', ')}`;
  return `test: generated Playwright coverage for ${ids.length} features`;
}

function buildBody(options: PrContentOptions): string {
  const lines: string[] = [];

  lines.push(...verdict(options.report));
  lines.push('');
  lines.push(`Generated by Flint against \`${options.baseUrl}\`.`);
  lines.push('');

  // ---- what ran ----------------------------------------------------------
  if (options.report === undefined) {
    lines.push('## Verification', '');
    lines.push(
      '**This suite was not run.** It typechecks, and nothing more than that is',
      'claimed. Run `flint verify` before merging.',
      '',
    );
  } else {
    const { summary } = options.report;
    lines.push('## What ran', '');
    lines.push('| Result | Count |', '| --- | ---: |');
    lines.push(`| Passed | ${summary.passed} |`);
    lines.push(`| Failed | ${summary.failed} |`);
    lines.push(`| Skipped | ${summary.skipped} |`);
    lines.push(`| Fixme | ${summary.fixme} |`);
    lines.push(`| Flaky | ${summary.flaky} |`);
    lines.push('');
    if (!options.report.envHealthy) {
      lines.push(
        '> The application was **not reachable** during this run, so nothing here',
        '> is evidence about the tests.',
        '',
      );
    }

    const notPassing = options.report.tests.filter((t) => t.status !== 'passed');
    if (notPassing.length > 0) {
      lines.push('### Not passing', '');
      for (const test of notPassing) {
        const why =
          test.failureClass !== undefined
            ? `${test.status} — ${test.failureClass}`
            : `${test.status}`;
        lines.push(`- \`${test.title}\` — ${why}`);
        const excerpt = firstLine(test.errorExcerpt);
        if (excerpt !== undefined) lines.push(`  > ${excerpt}`);
      }
      lines.push('');
    }

    const suspects = options.report.tests.filter((t) => t.possibleAppDefect === true);
    if (suspects.length > 0) {
      lines.push('### Possible application defects', '');
      lines.push(
        'These assertions failed on a value, not on a missing element. They may be',
        'real bugs rather than broken tests — worth a look before changing the test.',
        '',
      );
      for (const test of suspects) lines.push(`- \`${test.title}\``);
      lines.push('');
    }
  }

  // ---- what was planned --------------------------------------------------
  lines.push('## Coverage', '');
  for (const plan of [...options.plans].sort((a, b) => a.featureId.localeCompare(b.featureId))) {
    const live = plan.cases.filter((c) => c.status === 'new' || c.status === 'update-existing');
    const blocked = plan.cases.filter((c) => c.status === 'blocked');
    const duplicates = plan.cases.filter((c) => c.status === 'skipped-duplicate');

    lines.push(`### \`${plan.featureId}\``, '');
    for (const testCase of live) lines.push(`- ${testCase.title}`);
    if (live.length === 0) lines.push('- _(no new tests — every case was already covered)_');
    lines.push('');

    if (blocked.length > 0) {
      lines.push('Blocked — the Screen Model has no way to test these:', '');
      for (const testCase of blocked) {
        lines.push(`- ${testCase.title}${reason(testCase.blockedReason)}`);
      }
      lines.push('');
    }
    if (duplicates.length > 0) {
      lines.push(`${duplicates.length} case(s) skipped as duplicates of existing tests.`, '');
    }
  }

  lines.push('---', '');
  lines.push(
    '_Generated by [Flint](https://github.com/bishnu133/Flint). The suite is',
    'regenerated from `kb/features/*.md` and the Screen Model — edit those rather',
    'than the generated files, or edit a file and Flint will leave your version',
    'alone._',
  );

  return lines.join('\n');
}

/**
 * The first line of the body, and the only one some reviewers read.
 *
 * It is a claim about evidence, not a summary of effort: how many tests ran and
 * how many passed. "Adds 12 tests" says nothing about whether they work.
 */
function verdict(report: RunReport | undefined): string[] {
  if (report === undefined) return ['**Not verified** — generated and typechecked, but not run.'];
  if (!report.envHealthy) {
    return ['**Not verified** — the application was unreachable when this ran.'];
  }
  const ran = report.summary.passed + report.summary.failed;
  if (ran === 0) return ['**Nothing ran** — every test was skipped or marked fixme.'];
  if (report.summary.failed === 0) {
    return [`**${report.summary.passed} of ${ran} tests pass.**`];
  }
  return [`**${report.summary.passed} of ${ran} tests pass; ${report.summary.failed} fail.**`];
}

function reason(text: string | undefined): string {
  return text === undefined || text === '' ? '' : ` — ${text}`;
}

function firstLine(text: string | undefined): string | undefined {
  if (text === undefined || text === '') return undefined;
  const line = text.split('\n')[0]?.trim();
  return line === undefined || line === '' ? undefined : line.slice(0, 200);
}

/** The commit message for the generated change. */
export function commitMessage(featureIds: string[], report: RunReport | undefined): string {
  const ids = [...featureIds].sort();
  const subject =
    ids.length === 0
      ? 'test: regenerate the Playwright suite'
      : ids.length <= 3
        ? `test: generated Playwright coverage for ${ids.join(', ')}`
        : `test: generated Playwright coverage for ${ids.length} features`;

  const body =
    report === undefined
      ? 'Generated and typechecked. Not run.'
      : `${report.summary.passed} passed, ${report.summary.failed} failed, ` +
        `${report.summary.skipped} skipped, ${report.summary.fixme} fixme.`;

  return `${subject}\n\n${body}\n\nGenerated by Flint.`;
}
