import type {
  Dialect,
  EmittedAssertion,
  EmittedMethod,
  EmittedSelector,
  EmittedStatement,
  EmittedTest,
  PageObjectSpec,
  SpecFileSpec,
} from './types.js';

/**
 * The default dialect: plain Playwright with a Page Object Model.
 *
 * Output has zero runtime dependency on Flint (core principle #4) — it is
 * ordinary `@playwright/test` code that runs under `npx playwright test` with
 * Flint uninstalled.
 *
 * Everything here is a pure string transform. No clock, no filesystem: the
 * managed-marker hash and the byte-identical regeneration check both depend on
 * that.
 */

const INDENT = '  ';

export const playwrightPomDialect: Dialect = {
  name: 'playwright-pom',
  pageObjectDir: 'pages',
  specDir: 'tests',
  emitPageObject,
  emitSpec,
};

/** A TypeScript single-quoted string literal. */
export function quote(value: string): string {
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n');
  return `'${escaped}'`;
}

/**
 * The Playwright expression for a verified selector candidate.
 *
 * Each branch mirrors `locatorFor` in the extractor exactly. That is not
 * duplication for its own sake: the extractor's `count() === 1` check ran
 * against that expression, so any divergence here would emit a selector nobody
 * actually verified.
 */
export function locatorExpression(selector: EmittedSelector, root = 'this.page'): string {
  switch (selector.strategy) {
    case 'testid':
    case 'css':
      return `${root}.locator(${quote(selector.value)})`;
    case 'role': {
      const match = /^(.+?)\[name="(.*)"\]$/s.exec(selector.value);
      if (match === null) return `${root}.locator(${quote(selector.value)})`;
      return `${root}.getByRole(${quote(match[1]!)}, { name: ${quote(match[2]!)}, exact: true })`;
    }
    case 'label':
      return `${root}.getByLabel(${quote(selector.value)}, { exact: true })`;
    case 'placeholder':
      return `${root}.getByPlaceholder(${quote(selector.value)}, { exact: true })`;
    case 'text':
      return `${root}.getByText(${quote(selector.value)}, { exact: true })`;
  }
}

function emitPageObject(spec: PageObjectSpec): string {
  const lines: string[] = [
    `import type { Locator, Page } from '@playwright/test';`,
    '',
    '/**',
    ` * Page object for \`${spec.urlPattern}\`.`,
    ' *',
    ' * Generated by Flint from the Screen Model. Every locator below uses a',
    ' * selector that was verified against the live page during exploration.',
    ' */',
    `export class ${spec.className} {`,
    `${INDENT}readonly page: Page;`,
  ];

  for (const locator of spec.locators) {
    lines.push(`${INDENT}readonly ${locator.name}: Locator;`);
  }

  lines.push('', `${INDENT}constructor(page: Page) {`, `${INDENT}${INDENT}this.page = page;`);
  for (const locator of spec.locators) {
    // The strategy and score are recorded in code, per the LOCKED ranking
    // rules: a reviewer can see why this selector and not another.
    lines.push(
      `${INDENT}${INDENT}// ${locator.selector.description} — ${locator.selector.strategy} (score ${locator.selector.score}), ${locator.selector.elementId}`,
    );
    lines.push(`${INDENT}${INDENT}this.${locator.name} = ${locatorExpression(locator.selector)};`);
  }
  lines.push(`${INDENT}}`);

  lines.push('', `${INDENT}async goto(): Promise<void> {`);
  lines.push(`${INDENT}${INDENT}await this.page.goto(${quote(spec.url)});`);
  lines.push(`${INDENT}}`);

  for (const method of spec.methods) {
    lines.push('', ...renderMethod(method));
  }

  lines.push('}', '');
  return lines.join('\n');
}

function renderMethod(method: EmittedMethod): string[] {
  const params = method.parameters.map((p) => `${p}: string`).join(', ');
  const lines = [
    `${INDENT}/** ${method.summary} */`,
    `${INDENT}async ${method.name}(${params}): Promise<void> {`,
  ];
  for (const action of method.actions) {
    lines.push(`${INDENT}${INDENT}${renderAction(action)}`);
  }
  lines.push(`${INDENT}}`);
  return lines;
}

function renderAction(action: {
  kind: 'click' | 'fill' | 'select';
  locator: string;
  parameter?: string;
}): string {
  switch (action.kind) {
    case 'click':
      return `await this.${action.locator}.click();`;
    case 'fill':
      return `await this.${action.locator}.fill(${action.parameter ?? "''"});`;
    case 'select':
      return `await this.${action.locator}.selectOption(${action.parameter ?? "''"});`;
  }
}

function emitSpec(spec: SpecFileSpec): string {
  const imports = collectImports(spec.tests);
  const lines: string[] = [`import { test, expect } from '@playwright/test';`];
  for (const [importPath, classNames] of imports) {
    lines.push(`import { ${[...classNames].sort().join(', ')} } from ${quote(importPath)};`);
  }
  lines.push('', `test.describe(${quote(spec.title)}, () => {`);

  spec.tests.forEach((testCase, i) => {
    if (i > 0) lines.push('');
    lines.push(...renderTest(testCase).map((line) => (line === '' ? '' : `${INDENT}${line}`)));
  });

  lines.push('});', '');
  return lines.join('\n');
}

/** import path -> class names, in a stable order. */
function collectImports(tests: EmittedTest[]): Map<string, Set<string>> {
  const imports = new Map<string, Set<string>>();
  for (const testCase of tests) {
    for (const pageObject of testCase.pageObjects) {
      const existing = imports.get(pageObject.importPath) ?? new Set<string>();
      existing.add(pageObject.className);
      imports.set(pageObject.importPath, existing);
    }
  }
  return new Map([...imports.entries()].sort(([a], [b]) => a.localeCompare(b)));
}

function renderTest(testCase: EmittedTest): string[] {
  const lines: string[] = [];
  for (const note of testCase.notes) lines.push(`// ${note}`);
  lines.push(`// plan case: ${testCase.caseId}`);

  const title = quote(titleWithTags(testCase));

  if (testCase.mode.kind === 'fixme') {
    // A blocked case is a finding, not a silent gap: the reason travels into
    // the suite so whoever opens the file sees what exploration never saw.
    lines.push(`test.fixme(${title}, async () => {`);
    lines.push(`${INDENT}// ${testCase.mode.reason}`);
    // The plan's steps are real work against real element ids, and the case is
    // blocked on one missing thing. Dropping them would make whoever unblocks
    // it start over, so they are preserved as commented-out code.
    lines.push(...blockedSteps(testCase).map((line) => `${INDENT}${line}`));
    lines.push('});');
    return lines;
  }

  const opener = testCase.mode.kind === 'skip' ? 'test.skip' : 'test';
  lines.push(`${opener}(${title}, async ({ page }) => {`);

  for (const pageObject of testCase.pageObjects) {
    lines.push(`${INDENT}const ${pageObject.variable} = new ${pageObject.className}(page);`);
  }
  if (testCase.pageObjects.length > 0 && testCase.statements.length > 0) lines.push('');

  for (const statement of testCase.statements) {
    lines.push(...renderStatement(statement).map((line) => `${INDENT}${line}`));
  }
  lines.push('});');
  return lines;
}

/**
 * The steps the plan specified, as commented-out code.
 *
 * Rendered exactly as the live version would be, so unblocking the case is
 * uncommenting rather than rewriting.
 */
function blockedSteps(testCase: EmittedTest): string[] {
  if (testCase.statements.length === 0) return [];
  const lines = [
    '//',
    '// Steps the plan specified, once the blocker is resolved',
    '// (add `{ page }` to the test arguments to use them):',
  ];
  for (const pageObject of testCase.pageObjects) {
    lines.push(`// const ${pageObject.variable} = new ${pageObject.className}(page);`);
  }
  for (const statement of testCase.statements) {
    for (const rendered of renderStatement(statement)) lines.push(`// ${rendered}`);
  }
  return lines;
}

/**
 * Playwright has no tag argument in the plain `test()` signature that every
 * version supports, so tags ride in the title — which is also how the Suite
 * Indexer reads them back (Phase 2), keeping one convention across both.
 */
function titleWithTags(testCase: EmittedTest): string {
  const tags = [...testCase.tags].sort();
  return tags.length === 0 ? testCase.title : `${testCase.title} ${tags.join(' ')}`;
}

function renderStatement(statement: EmittedStatement): string[] {
  switch (statement.kind) {
    case 'goto':
      // A page object owns its own URL, so the test reads as intent rather than
      // repeating a literal the page object already has.
      return statement.pageVariable === undefined
        ? [`await page.goto(${quote(statement.url)});`]
        : [`await ${statement.pageVariable}.goto();`];
    case 'call':
      return [
        `await ${statement.pageVariable}.${statement.method}(${statement.args.map(quote).join(', ')});`,
      ];
    case 'comment':
      return [`// ${statement.text}`];
    case 'assert':
      return [renderAssertion(statement.assertion)];
  }
}

function renderAssertion(assertion: EmittedAssertion): string {
  const target =
    assertion.target === undefined
      ? undefined
      : `${assertion.target.pageVariable}.${assertion.target.locator}`;

  switch (assertion.kind) {
    case 'visible':
      return assertion.expected === false
        ? `await expect(${target}).toBeHidden();`
        : `await expect(${target}).toBeVisible();`;
    case 'hidden':
      return `await expect(${target}).toBeHidden();`;
    case 'text':
    case 'toast':
      return `await expect(${target}).toHaveText(${quote(String(assertion.expected))});`;
    case 'value':
      return `await expect(${target}).toHaveValue(${quote(String(assertion.expected))});`;
    case 'count':
      return `await expect(${target}).toHaveCount(${Number(assertion.expected)});`;
    case 'url':
      return `await expect(page).toHaveURL(${quote(String(assertion.expected))});`;
  }
}
